language: cpp
script: make release-static
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libssl-dev
      - libboost-all-dev
      - build-essential
      - cmake
      - pkg-config
      - libunbound-dev
